const Data = [
	"This book covers how to write automated tests to confirm that our software works. It also shows how to use the various concurrency libraries available as part of Python; this lets us write software that can make use of multiple cores and multiple processors in a modern computer. An extended case study covers a simple machine learning example, showing a number of alternative solutions to a moderately complicated problem",
	"This book targets people who are new to object-oriented programming in Python.It assumes basic Python skills. For readers with a background in another objectoriented programming language, this book will expose many distinctive features of Python's approach",
	"This book is divided into four overall sections. The first six chapters provide the core principles and concepts of object-oriented programming and how these are implemented in Python. The next three chapters take a close look at Python builtin features through the lens of object-oriented programming. Chapters 10, 11, and 12 look at a number of common design patterns and how these can be handled in Python. The final section covers two additional topics: testing and concurrency",
	"Chapter 1, Object-Oriented Design, introduces the core concepts underlying objectoriented design. This provides a road map through the ideas of state and behavior, attributes and methods, and how objects are grouped into classes. This chapter also looks an encapsulation, inheritance, and composition. The case study for this chapter introduces the machine learning problem, which is an implementation of a k-nearest neighbors (k-NN) classifier",
	"Once you've read Python Object-Oriented Programming, Fourth Edition, we'd love tohear your thoughts! Please click here to go straight to the Amazon review page for this book and share your feedback. Your review is important to us and the tech community and will help us make sure we're delivering excellent quality content.",
	"The output of the analysis stage is a description of the system, often in the formof requirements. If we were to complete the analysis stage in one step, we wouldhave turned a task, such as As a botanist, I need a website to help users classify plants so I can help with correct identification, into a set of required features. As an example, here are some requirements as to what a website visitor might need to do. Each item is an action bound to an object; we've written them with italics to highlight the actions, and bold to highlight the objects:",
	"Rest of this book is about object-oriented programming, but in this chapter, we will cover the basic object-oriented principles in the context of design. This allows us to understand concepts without having to argue with software syntax or Python tracebacks"
]
export default Data;